# Generated by Django 5.0.2 on 2024-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Стоимость'),
        ),
    ]
