# Generated by Django 5.0.2 on 2024-03-11 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adress",
            name="number_apt",
        ),
    ]
