# Generated by Django 5.0.2 on 2024-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='number',
            field=models.IntegerField(),
        ),
    ]
