# Generated by Django 5.0.2 on 2024-03-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('new', 'Новый'), ('inprocess', 'В процессе'), ('onaway', 'В пути'), ('delivered', 'Доставлено'), ('cancel', 'Отменено')], default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='StatusDeliver',
        ),
    ]
