# Generated by Django 5.0.2 on 2024-03-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('deliveries', '0002_alter_delivery_delivery_status_delete_statusdeliver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_cost',
            new_name='order_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_address', to='customers.adress'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_cart', to='customers.cart'),
        ),
    ]
