# Generated by Django 5.0.2 on 2024-03-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
