# Generated by Django 5.0.2 on 2024-03-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(max_length=25),
        ),
    ]
