# Generated by Django 5.0.2 on 2024-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
